In [2]:
import numpy as np

# 1.1. Создание одномерного массива с числами до 100, кратными 5
my_array = np.arange(5, 101, 5)
print("1.1. Одномерный массив с числами, кратными 5:\n", my_array)

# 2.1. Получение массива с кратными 10 числами
my_array_10 = my_array[my_array % 10 == 0]
print("\n2.1. Массив с числами, кратными 10:\n", my_array_10)

# 3.1. Преобразование в двумерный массив с двумя столбцами
my_array_2d = my_array_10.reshape(-1, 2)
print("\n3.1. Двумерный массив с двумя столбцами:\n", my_array_2d)

# 4.1. Создание нового массива, где каждый элемент на 5 меньше исходного
my_second_array = my_array - 5
my_second_array_2d = my_second_array.reshape(-1, 2)
print("\n4.1. Двумерный массив, где каждый элемент на 5 меньше исходного:\n", my_second_array_2d)

# 5.1. Соединение массивов горизонтально с транспонированием
combined_array = np.hstack((my_array_2d.T, my_second_array_2d.T)).T
print("\n5.1. Соединённый массив после транспонирования:\n", combined_array)

# 6.1. Деление 2 и 3 строки на 4 верхних строки (с подавлением деления на 0)
with np.errstate(divide='ignore', invalid='ignore'):
    division_result = combined_array.T[1:3] / combined_array.T[:4]
    division_result[np.isinf(division_result)] = np.nan  # Замена деления на 0 на np.nan
print("\n6.1. Результат деления второй и третьей строк на первые четыре:\n", division_result)

# 7.1. Оставляем только значения, которые не изменились после деления
unchanged_values = division_result[division_result == 1]
print("\n7.1. Значения, которые не изменились после деления (равные 1):\n", unchanged_values)

# 8.1. Получаем новый массив и меняем местами первую и третью строки
modified_array = combined_array.copy()
modified_array[[0, 2]] = modified_array[[2, 0]]
print("\n8.1. Массив с заменёнными строками (первая и третья строки поменяны местами):\n", modified_array)

# 9.1. Вычисление среднего, медианы и стандартного отклонения для каждой строки
mean_values = np.mean(modified_array, axis=1)
median_values = np.median(modified_array, axis=1)
std_values = np.std(modified_array, axis=1)
print("\n9.1. Среднее значение для каждой строки:\n", mean_values)
print("Медиана для каждой строки:\n", median_values)
print("Стандартное отклонение для каждой строки:\n", std_values)

# 10.1. Нормализация на максимальное значение вдоль строк
normalized_array = modified_array / np.max(modified_array, axis=1, keepdims=True)
print("\n10.1. Нормализованный массив (деление на максимальное значение в строке):\n", normalized_array)


1.1. Одномерный массив с числами, кратными 5:
 [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]

2.1. Массив с числами, кратными 10:
 [ 10  20  30  40  50  60  70  80  90 100]

3.1. Двумерный массив с двумя столбцами:
 [[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]]

4.1. Двумерный массив, где каждый элемент на 5 меньше исходного:
 [[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]
 [60 65]
 [70 75]
 [80 85]
 [90 95]]

5.1. Соединённый массив после транспонирования:
 [[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]
 [  0   5]
 [ 10  15]
 [ 20  25]
 [ 30  35]
 [ 40  45]
 [ 50  55]
 [ 60  65]
 [ 70  75]
 [ 80  85]
 [ 90  95]]

6.1. Результат деления второй и третьей строк на первые четыре:
 [[2.         1.33333333 1.2        1.14285714 1.11111111        nan
  1.5        1.25       1.16666667 1.125      1.1        1.08333333
  1.07142857 1.0625     1.05555556]
 [1.         1.         1.         1.         1.         1.
  1.         1.    

# Анализ глобальных тенденций населения (2016-2022)

В этом блокноте мы будем анализировать данные о глобальном населении за период с 2016 по 2022 год.

## Импортируем необходимые библиотеки



In [4]:
# 1. Подключите библиотеку pandas
import pandas as pd

# 2.1. Импортируйте данные из файла “Global Population Trends(2016-2022).csv”
df = pd.read_csv("Global Population Trends(2016-2022).csv")

# 2.2. Считайте несколько первых записей таблицы
print("Первые записи таблицы:")
print(df.head())

# 2.3. Определите размерность данного фрейма
print("\nРазмерность фрейма:")
print(df.shape)

# 2.4. Выведите название заголовков столбцов фрейма
print("\nНазвание заголовков столбцов:")
print(df.columns)

# 2.5. Получите описание всех переменных
print("\nОписание всех переменных:")
print(df.info())

# 2.6. Удалите строки, не содержащие значения в столбце «Total Population»
df1 = df[df['Total Population'] != '-']

# Удаление запятых и преобразование в целое число
df1.loc[:, 'Total Population'] = df1['Total Population'].str.replace(',', '').astype(int)

# 2.7. Получите описательную статистику по переменным
print("\nОписательная статистика по переменным:")
print(df1.describe())
print(df1.max())
print(df1.min())

# 2.8. Выполните сортировку данных по нескольким критериям
df_sorted = df1.sort_values(by=['Country', 'Total Population'], ascending=[True, False])
print("\nОтсортированные данные:")
print(df_sorted.head())

# 2.9. Выведите название страны, которая имеет максимальную численность населения
max_population_country = df1.loc[df1['Total Population'].idxmax(), 'Country']
print("\nСтрана с максимальной численностью населения:", max_population_country)

# 2.10. Выведите название страны, которая имеет минимальную численность населения
min_population_country = df1.loc[df1['Total Population'].idxmin(), 'Country']
print("Страна с минимальной численностью населения:", min_population_country)

# 2.11. Экспорт фрейма в MS Excel
df1.to_excel("Global_Population_Stats.xlsx", index=False)
print("\nФрейм экспортирован в MS Excel как 'Global_Population_Stats.xlsx'")


Первые записи таблицы:
       Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55              63      37.342       7.027          5.129   
1                 56              63      36.927       6.981          5.002   
2                 58              64      36.466       6.791           4.87   
3                 60              63      36.051       7.113           4.75   
4                  -              62      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0            